fields = [
    "name",
    "gender",
    "date_of_birth",
    "father_name",
    "mother_name",
    "category",
    "physically_handicapped",
    "region",
    "state",
    "city",
    "school",
    "course",
    "stream",
    "grade",
    "email",
    "phone_number",
    "alternate_phone_number",
    "family_income",
]
grade_code = {"12": "23", "11": "24", "10": "25", "9": "26"}
