from settings import settings

student_db_url = settings.db_url + "/student"
group_db_url = settings.db_url + "/group"
group_type_db_url = settings.db_url + "/group-type/"
group_user_db_url = settings.db_url + "/group-user"
enrollment_record_db_url = settings.db_url + "/enrollment-record"
form_db_url = settings.db_url + "/form-schema"
user_db_url = settings.db_url + "/user"
school_db_url = settings.db_url + "/school"
batch_db_url = settings.db_url + "/batch/"
user_session_db_url = settings.db_url + "/user-session/"
exam_db_url = settings.db_url + "/exam"
student_exam_record_db_url = settings.db_url + "/student-exam-record"
teacher_db_url = settings.db_url + "/teacher"
