from settings import settings

auth_group_db_url = settings.db_url + "/auth-group"
batch_db_url = settings.db_url + "/batch/"
enrollment_record_db_url = settings.db_url + "/enrollment-record"
form_db_url = settings.db_url + "/form-schema"
grade_db_url = settings.db_url + "/grade"
exam_db_url = settings.db_url + "/exam"
group_user_db_url = settings.db_url + "/group-user"
group_db_url = settings.db_url + "/group/"
program_db_url = settings.db_url + "/program"
school_db_url = settings.db_url + "/school"
group_session_db_url = settings.db_url + "/group-session"
session_occurrence_db_url = settings.db_url + "/session-occurrence"
abtest_db_url = settings.db_url + "/abtest"
session_db_url = settings.db_url + "/session"
student_db_url = settings.db_url + "/student"
subject_db_url = settings.db_url + "/subject"
teacher_db_url = settings.db_url + "/teacher"
candidate_db_url = settings.db_url + "/candidate"
user_session_db_url = settings.db_url + "/user-session/"
user_db_url = settings.db_url + "/user"
