AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Portal Backend - Prod

Parameters:
  JwtSecretKey:
    Type: String
    Description: Key to generate tokens

  DbServiceUrl:
    Type: String
    Description: URL for the DB service

  DbServiceToken:
    Type: String
    Description: Token to access DB Service

  SqsAccessKey:
    Type: String
    Description: Key to send SQS messages

  SqsSecretAccessKey:
    Type: String
    Description: Key to send SQS messages

  AwsSqsUrl:
    Type: String
    Description: Url to send SQS message for attendance logging

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "PortalBackendProd"
      CodeUri: ../app
      Handler: main.handler
      Runtime: python3.9
      Timeout: 10
      Environment:
        Variables:
          JWT_SECRET_KEY: !Ref JwtSecretKey
          DB_SERVICE_URL: !Ref DbServiceUrl
          DB_SERVICE_TOKEN: !Ref DbServiceToken
          SQS_ACCESS_KEY: !Ref SqsAccessKey
          SQS_SECRET_ACCESS_KEY: !Ref SqsSecretAccessKey
          AWS_SQS_URL: !Ref AwsSqsUrl
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi

Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
