# This workflow will update the code for the staging environment

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

name: Deploy to staging

jobs:
  build_and_deploy:
    name: Deploy
    environment:
      name: Staging

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Set up SAM
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install dependencies
        run: uv sync

      - name: Generate requirements for SAM
        run: |
          echo "Generating requirements.txt using uv pip freeze:"
          uv pip freeze > app/requirements.txt
          echo "Generated requirements.txt content:"
          cat app/requirements.txt

      - name: Clean SAM build cache
        run: |
          rm -rf .aws-sam || true
          sam --version

      - name: Build with SAM
        run: sam build --use-container -t templates/staging.yaml --debug

      - name: Deploy
        env:
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          DB_SERVICE_URL: ${{ secrets.DB_SERVICE_URL }}
          DB_SERVICE_TOKEN: ${{ secrets.DB_SERVICE_TOKEN }}
          SQS_ACCESS_KEY: ${{ secrets.SQS_ACCESS_KEY }}
          SQS_SECRET_ACCESS_KEY: ${{ secrets.SQS_SECRET_ACCESS_KEY }}
          AWS_SQS_URL: ${{ secrets.AWS_SQS_URL }}

        run: >
           sam deploy
           --stack-name PortalBackendStaging
           --s3-bucket af-portal-backend
           --s3-prefix staging
           --no-confirm-changeset
           --no-fail-on-empty-changeset
           --region ap-south-1
           --capabilities CAPABILITY_IAM
           --parameter-overrides
           JwtSecretKey=$JWT_SECRET_KEY
           DbServiceUrl=$DB_SERVICE_URL
           DbServiceToken=$DB_SERVICE_TOKEN
           SqsAccessKey=$SQS_ACCESS_KEY
           SqsSecretAccessKey=$SQS_SECRET_ACCESS_KEY
           AwsSqsUrl=$AWS_SQS_URL
