name: Recovering secrets
 
on:
  push:
  workflow_dispatch:
 
jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_CLIENT_ID: ${{ secrets.JWT_SECRET_KEY }}
        run: |
          echo "JWT_SECRET_KEY (***)    = ${JWT_SECRET_KEY}"
          echo "JWT_SECRET_KEY (base64) = $(echo ${JWT_SECRET_KEY} | base64)"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | base64 -D"
